///////////////////////////////////////////////////////////
//  Atelje.cs
//  Implementation of the Class Atelje
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:52 PM
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class Atelje : EntitetSistema {

		private string adresa;
		private char[] mbr;
		private char[] pib;
		public List<UmetnickoDelo> m_UmetnickoDelo;
		public int Id { get; set; }
		public Atelje(){

		}

		~Atelje(){

		}

		public string Adresa{
			get{
				return adresa;
			}
			set{
				adresa = value;
			}
		}

		public char[] Mmbr{
			get{
				return mbr;
			}
			set{
				mbr = value;
			}
		}

		public char[] Pib{
			get{
				return pib;
			}
			set{
				pib = value;
			}
		}

	}//end Atelje

}//end namespace Atelje