///////////////////////////////////////////////////////////
//  Autor.cs
//  Implementation of the Class Autor
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:52 PM
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class Autor : EntitetSistema {

		private DateTime godinaRodjenja;
		private DateTime? godinaSmrti;
		private int id;
		private string ime;
		private string prezime;
		private UmetnickiPravac umetnickiPravac;
		public List<UmetnickoDelo> m_UmetnickoDelo;

		public Autor(){

		}

		~Autor(){

		}

		public DateTime GodinaRodjenja{
			get{
				return godinaRodjenja;
			}
			set{
				godinaRodjenja = value;
			}
		}

		public DateTime? GodinaSmrti{
			get{
				return godinaSmrti;
			}
			set{
				godinaSmrti = value;
			}
		}

		public int Id{
			get{
				return id;
			}
			set{
				id = value;
			}
		}

		public string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

		public string Prezime{
			get{
				return prezime;
			}
			set{
				prezime = value;
			}
		}

		public UmetnickiPravac UmetnickiPravac{
			get{
				return umetnickiPravac;
			}
			set{
				umetnickiPravac = value;
			}
		}

	}//end Autor

}//end namespace Atelje