///////////////////////////////////////////////////////////
//  EntitetSistema.cs
//  Implementation of the Class EntitetSistema
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:52 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Atelje {
	public abstract class EntitetSistema {

		public EntitetSistema(){

		}

		~EntitetSistema(){

		}

	}//end EntitetSistema

}//end namespace Atelje