///////////////////////////////////////////////////////////
//  EntitetFactory.cs
//  Implementation of the Class EntitetFactory
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:53 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public abstract class EntitetFactory {

		public EntitetFactory(){

		}

		~EntitetFactory(){

		}

		public abstract EntitetSistema MakeEntitet();

	}//end EntitetFactory

}//end namespace Atelje