///////////////////////////////////////////////////////////
//  IKorisnikLog.cs
//  Implementation of the Interface IKorisnikLog
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:55 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public interface IKorisnikLog  {

		/// 
		/// <param name="log"></param>
		/// <param name="idKorisnika"></param>
		void UpisiLog(LogPodatak log, int idKorisnika);
	}//end IKorisnikLog

}//end namespace Atelje