///////////////////////////////////////////////////////////
//  ISistemLog.cs
//  Implementation of the Interface ISistemLog
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:54 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public interface ISistemLog  {

		/// 
		/// <param name="log"></param>
		void UpisiLog(LogPodatak log);
	}//end ISistemLog

}//end namespace Atelje