///////////////////////////////////////////////////////////
//  KorisnikSistema.cs
//  Implementation of the Class KorisnikSistema
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:53 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class KorisnikSistema : EntitetSistema {

		private string email;
		private int id;
		private string ime;
		private string korisnickoIme;
		private string lozinkaHash;
		private string prezime;
		private TipKorisnika tipKorisnika;

		public KorisnikSistema(){

		}

		~KorisnikSistema(){

		}

		public string Email{
			get{
				return email;
			}
			set{
				email = value;
			}
		}

		public int Id{
			get{
				return id;
			}
			set{
				id = value;
			}
		}

		public string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

		public string KorisnickoIme{
			get{
				return korisnickoIme;
			}
			set{
				korisnickoIme = value;
			}
		}

		public string LozinkaHash{
			get{
				return lozinkaHash;
			}
			set{
				lozinkaHash = value;
			}
		}

		public string Prezime{
			get{
				return prezime;
			}
			set{
				prezime = value;
			}
		}

		public TipKorisnika TipKorisnika{
			get{
				return tipKorisnika;
			}
			set{
				tipKorisnika = value;
			}
		}

	}//end KorisnikSistema

}//end namespace Atelje