///////////////////////////////////////////////////////////
//  KorisnikLogCSV.cs
//  Implementation of the Class KorisnikLogCSV
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:55 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class KorisnikLogCSV : IKorisnikLog {

		public KorisnikLogCSV(){

		}

		~KorisnikLogCSV(){

		}

        public void IzmeniImeFajla(int prevId, int newId)
        {
			var logDir = Directory.GetCurrentDirectory();

			var pathPrev = Path.Combine(logDir, "UsersLog", String.Format("{0}.csv", prevId));

			var content = File.ReadAllText(pathPrev);

			File.Delete(pathPrev);

			var pathNew = Path.Combine(logDir, "UsersLog", String.Format("{0}.csv", newId));
			File.WriteAllText(pathNew, content);
		}

		/// 
		/// <param name="log"></param>
		/// <param name="idKorisnika"></param>
		public void UpisiLog(LogPodatak log, int idKorisnika){
			var logDir = Directory.GetCurrentDirectory();

			var pathLog = Path.Combine(logDir, "UsersLog", String.Format("{0}.csv", idKorisnika));

			var csv = String.Format("{0},{1},{2}\n",
				log.Vreme.ToString(), Enum.GetName(typeof(LogTip), log.Tip), log.Poruka);

			File.AppendAllText(pathLog, csv);

		}



	}//end KorisnikLogCSV

}//end namespace Atelje