///////////////////////////////////////////////////////////
//  KorisnikLogCSV.cs
//  Implementation of the Class KorisnikLogCSV
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:55 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class KorisnikLogCSV : IKorisnikLog {

		public KorisnikLogCSV(){

		}

		~KorisnikLogCSV(){

		}

		/// 
		/// <param name="log"></param>
		/// <param name="idKorisnika"></param>
		public void UpisiLog(LogPodatak log, int idKorisnika){

		}

	}//end KorisnikLogCSV

}//end namespace Atelje