///////////////////////////////////////////////////////////
//  LogPodatak.cs
//  Implementation of the Class LogPodatak
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:54 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class LogPodatak {

		private string poruka;
		private LogTip tip;
		private DateTime vreme;
		public IKorisnikLog korisnikLog { get; set; }
		public ISistemLog sistemLog { get; set; }

		public LogPodatak(IKorisnikLog korisnikLog, ISistemLog sistemLog){
			this.korisnikLog = korisnikLog;
			this.sistemLog = sistemLog;
		}

		~LogPodatak(){

		}

		public string Poruka{
			get{
				return poruka;
			}
			set{
				poruka = value;
			}
		}

		public LogTip Tip{
			get{
				return tip;
			}
			set{
				tip = value;
			}
		}

		public DateTime Vreme{
			get{
				return vreme;
			}
			set{
				vreme = value;
			}
		}

	}//end LogPodatak

}//end namespace Atelje