///////////////////////////////////////////////////////////
//  LogTip.cs
//  Implementation of the Enumeration LogTip
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:54 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Atelje {
	public enum LogTip : int {

		DEBUG,
		INFO,
		WARN,
		ERROR,
		FATAL

	}//end LogTip

}//end namespace Atelje