///////////////////////////////////////////////////////////
//  SistemLogCSV.cs
//  Implementation of the Class SistemLogCSV
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:55 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class SistemLogCSV : ISistemLog {

		public SistemLogCSV(){

		}

		~SistemLogCSV(){

		}

		/// 
		/// <param name="log"></param>
		public void UpisiLog(LogPodatak log){

		}

	}//end SistemLogCSV

}//end namespace Atelje