///////////////////////////////////////////////////////////
//  Stil.cs
//  Implementation of the Enumeration Stil
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:56 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Atelje {
	public enum Stil : int {

		Pejzaz,
		MrtvaPriroda,
		Portret,
		FigurativnoSlikarstvo,
		Apstrakcija

	}//end Stil

}//end namespace Atelje