///////////////////////////////////////////////////////////
//  TipKorisnika.cs
//  Implementation of the Enumeration TipKorisnika
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:54 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Atelje {
	public enum TipKorisnika : int {

		ADMIN,
		KORISNIK

	}//end TipKorisnika

}//end namespace Atelje