///////////////////////////////////////////////////////////
//  UmetnickiPravac.cs
//  Implementation of the Enumeration UmetnickiPravac
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:56 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Atelje {
	public enum UmetnickiPravac : int {

		Barok,
		Klasicizam,
		Kubizam,
		Renesansa,
		Romantizam,
		Impresionizam,
		Ekspresionizam

	}//end UmetnickiPravac

}//end namespace Atelje