///////////////////////////////////////////////////////////
//  UmetnickoDeloFactory.cs
//  Implementation of the Class UmetnickoDeloFactory
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:53 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class UmetnickoDeloFactory : EntitetFactory {

		public UmetnickoDeloFactory(){

		}

		~UmetnickoDeloFactory(){

		}

		public override EntitetSistema MakeEntitet(){

			return new UmetnickoDelo();
		}

	}//end UmetnickoDeloFactory

}//end namespace Atelje