///////////////////////////////////////////////////////////
//  UmetnickoDelo.cs
//  Implementation of the Class UmetnickoDelo
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 5:00:55 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class UmetnickoDelo : EntitetSistema {

		private int id;
		private string naziv;
		private UmetnickiPravac pravac;
		private Stil stil;
		public int IdAtelje { get; set; }
		public int IdUmetnik { get; set; }
		public UmetnickoDelo(){

		}

		~UmetnickoDelo(){

		}

		public int Id{
			get{
				return id;
			}
			set{
				id = value;
			}
		}

		public string Naziv{
			get{
				return naziv;
			}
			set{
				naziv = value;
			}
		}

		public UmetnickiPravac Pravac{
			get{
				return pravac;
			}
			set{
				pravac = value;
			}
		}

		public Stil Stil{
			get{
				return stil;
			}
			set{
				stil = value;
			}
		}

	}//end UmetnickoDelo

}//end namespace Atelje