///////////////////////////////////////////////////////////
//  DBConvertKorisnik.cs
//  Implementation of the Class DBConvertKorisnik
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 6:14:08 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


using DBAccess;
using Atelje;
namespace Atelje {
	public class DBConvertKorisnik : IDBConvert {

		public DBConvertKorisnik(){

		}

		~DBConvertKorisnik(){

		}

		/// 
		/// <param name="webModel"></param>
		public DBEntity ConvertToDBModel(EntitetSistema webModel){
            try
            {
				var k = (KorisnikSistema)webModel;

				return new DBAccess.KorisnikSistema()
				{
					Email = k.Email,
					Id = k.Id,
					Ime = k.Ime,
					KorisnickoIme = k.KorisnickoIme,
					LozinkaHash = k.LozinkaHash,
					Prezime = k.Prezime,
					TipKorisnika = (int)k.TipKorisnika
				};
            }
            catch (Exception)
            {
				return null;
            }
			
		}

		/// 
		/// <param name="dbModel"></param>
		public EntitetSistema ConvertToWebModel(DBEntity dbModel){
            try
            {
				var k = (DBAccess.KorisnikSistema)dbModel;

				return new KorisnikSistema()
				{
					Email = k.Email,
					Id = k.Id,
					Ime = k.Ime,
					KorisnickoIme = k.KorisnickoIme,
					LozinkaHash = k.LozinkaHash,
					Prezime = k.Prezime,
					TipKorisnika = (TipKorisnika)k.TipKorisnika
				};
            }
            catch (Exception)
            {
				return null;
			}
		}

	}//end DBConvertKorisnik

}//end namespace Atelje