///////////////////////////////////////////////////////////
//  DBConvertUmetnickoDelo.cs
//  Implementation of the Class DBConvertUmetnickoDelo
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:23 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


using DBAccess;
using Atelje;
namespace Atelje {
	public class DBConvertUmetnickoDelo : IDBConvert {

		public DBConvertUmetnickoDelo(){

		}

		~DBConvertUmetnickoDelo(){

		}

		/// 
		/// <param name="webModel"></param>
		public DBEntity ConvertToDBModel(EntitetSistema webModel){
            try
            {
				var ud = (UmetnickoDelo)webModel;
				return new DBAccess.UmetnickoDelo()
				{
					Id = ud.Id,
					Naziv = ud.Naziv,
					Pravac = (int)ud.Pravac,
					Stil = (int)ud.Stil,
					AteljeId = ud.IdAtelje,
					AutorId = ud.IdUmetnik
				};
            }
            catch (Exception)
            {
				return null;
            }
		}

		/// 
		/// <param name="dbModel"></param>
		public EntitetSistema ConvertToWebModel(DBEntity dbModel){
            try
            {
				var ud = (DBAccess.UmetnickoDelo)dbModel;
				return new UmetnickoDelo()
				{
					Id = ud.Id,
					Naziv = ud.Naziv,
					Pravac = (UmetnickiPravac)ud.Pravac,
					Stil = (Stil)ud.Stil,
					IdAtelje = (int)ud.AteljeId,
					IdUmetnik = ud.AutorId
				};
            }
            catch (Exception)
            {
				return null;
            }
		}

	}//end DBConvertUmetnickoDelo

}//end namespace Atelje