///////////////////////////////////////////////////////////
//  DBCRUDAteljeRead.cs
//  Implementation of the Class DBCRUDAteljeRead
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:25 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class DBCRUDAteljeRead : DBCRUDAteljeCommand {

		private List<EntitetSistema> entitet;

		public DBCRUDAteljeRead(){

		}

		~DBCRUDAteljeRead(){

		}

		public List<EntitetSistema> Entiteti{
			get{
				return entiteti;
			}
		}

		public void Execute(){

		}

		public List<EntitetSistema> Read(){

			return null;
		}

	}//end DBCRUDAteljeRead

}//end namespace Atelje