///////////////////////////////////////////////////////////
//  DBCRUDUmetnickoDelo.cs
//  Implementation of the Class DBCRUDUmetnickoDelo
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:24 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using DBAccess;

using Atelje;
using System.Linq;

namespace Atelje {
	public class DBCRUDUmetnickoDelo : DBCRUD {

		public DBCRUDUmetnickoDelo(){

		}

		~DBCRUDUmetnickoDelo(){

		}

		/// 
		/// <param name="entitet"></param>
		public override void Create(EntitetSistema entitet){
			AteljeDB db;
            lock (db = AteljeDB.Instance())
            {
				konverzija = new DBConvertUmetnickoDelo();

				db.UmetnickoDeloes.Add((DBAccess.UmetnickoDelo)konverzija.ConvertToDBModel(entitet));
				db.SaveChanges();
			}
		}
		
		/// 
		/// <param name="id"></param>
		public override void Delete(int id){
			AteljeDB db;

            lock (db = AteljeDB.Instance())
            {
				var delo = db.UmetnickoDeloes.Where(x => x.Id == id);

				if (delo.Count() > 0)
				{
					db.UmetnickoDeloes.Remove(delo.First());
					db.SaveChanges();
				}
			}
		}

		public override List<EntitetSistema> Read(){
			var retVal = new List<EntitetSistema>();

			AteljeDB db;

            lock (db = AteljeDB.Instance())
            {
				konverzija = new DBConvertUmetnickoDelo();

                foreach (var d in db.UmetnickoDeloes)
                {
					retVal.Add(konverzija.ConvertToWebModel(d));
                }
            }

			return retVal;
		}

		/// 
		/// <param name="noviEntitet"></param>
		public override void Update(EntitetSistema noviEntitet) {
			var d = (UmetnickoDelo)noviEntitet;
			AteljeDB db;
            lock (db = AteljeDB.Instance())
            {
				var deloQ = db.UmetnickoDeloes.Where(x => x.Id == d.Id);

				if (deloQ.Count() > 0)
				{
					konverzija = new DBConvertUmetnickoDelo();

					db.UmetnickoDeloes.Remove(deloQ.First());
					var dbEnt = (DBAccess.UmetnickoDelo)konverzija.ConvertToDBModel(d);
					db.UmetnickoDeloes.Add(dbEnt);
					db.SaveChanges();
				}
			}
		}

	}//end DBCRUDUmetnickoDelo

}//end namespace Atelje