///////////////////////////////////////////////////////////
//  DBCRUDUmetnickoDelo.cs
//  Implementation of the Class DBCRUDUmetnickoDelo
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:24 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class DBCRUDUmetnickoDelo : DBCRUD {

		public DBCRUDUmetnickoDelo(){

		}

		~DBCRUDUmetnickoDelo(){

		}

		/// 
		/// <param name="entitet"></param>
		public void Create(EntitetSistema entitet){

		}

		/// 
		/// <param name="id"></param>
		public void Delete(int id){

		}

		public List<EntitetSistema> Read(){

			return null;
		}

		/// 
		/// <param name="noviEntitet"></param>
		public void Update(EntitetSistema noviEntitet){

		}

	}//end DBCRUDUmetnickoDelo

}//end namespace Atelje