///////////////////////////////////////////////////////////
//  DBCRUDAteljeUpdate.cs
//  Implementation of the Class DBCRUDAteljeUpdate
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:25 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class DBCRUDAteljeUpdate : DBCRUDAteljeCommand {

		private EntitetSistema entitetPosle;
		private EntitetSistema entitetPre;

		public DBCRUDAteljeUpdate(){

		}

		~DBCRUDAteljeUpdate(){

		}

		public EntitetSistema EntitetPosle{
			get{
				return entitetPosle;
			}
			set{
				entitetPosle = value;
			}
		}

		public EntitetSistema EntitetPre{
			get{
				return entitetPre;
			}
			set{
				entitetPre = value;
			}
		}

		public void Execute(){

		}

		public void Unexecute(){

		}

		/// 
		/// <param name="noviEntiteti"></param>
		public void Update(EntitetSistema noviEntiteti){

		}

	}//end DBCRUDAteljeUpdate

}//end namespace Atelje