///////////////////////////////////////////////////////////
//  DBCRUDAteljeDelete.cs
//  Implementation of the Class DBCRUDAteljeDelete
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:26 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class DBCRUDAteljeDelete : DBCRUDAteljeCommand {

		private EntitetSistema entitet;

		public DBCRUDAteljeDelete(){

		}

		~DBCRUDAteljeDelete(){

		}

		/// 
		/// <param name="entitet"></param>
		public void Create(EntitetSistema entitet){

		}

		/// 
		/// <param name="id"></param>
		public override void Delete(int id){

		}

		public EntitetSistema Entitet{
			get{
				return entitet;
			}
			set{
				entitet = value;
			}
		}

		public override void Execute(){

		}

		public override void Unexecute(){

		}

	}//end DBCRUDAteljeDelete

}//end namespace Atelje