///////////////////////////////////////////////////////////
//  DBCRUD.cs
//  Implementation of the Class DBCRUD
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:25 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


using Atelje;
namespace Atelje {
	public abstract class DBCRUD {

		protected IDBConvert konverzija;
		protected readonly object crudLock = new object();

		public DBCRUD(){

		}

		~DBCRUD(){

		}

		/// 
		/// <param name="entitet"></param>
		public virtual void Create(EntitetSistema entitet) { }

		/// 
		/// <param name="id"></param>
		public virtual void Delete(int id) { }

		public virtual List<EntitetSistema> Read() { return null; }

		/// 
		/// <param name="entitet"></param>
		public virtual void Update(EntitetSistema entitet) { }

	}//end DBCRUD

}//end namespace Atelje