///////////////////////////////////////////////////////////
//  DBCRUDUmetnik.cs
//  Implementation of the Class DBCRUDUmetnik
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:24 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using DBAccess;

using Atelje;
using System.Linq;

namespace Atelje {
	public class DBCRUDUmetnik : DBCRUD {

		public DBCRUDUmetnik(){

		}

		~DBCRUDUmetnik(){

		}

		/// 
		/// <param name="entitet"></param>
		public override void Create(EntitetSistema entitet){
            using (var db = AteljeDB.Instance())
            {
				IDBConvert convert = new DBConvertAutor();

				db.Autors.Add((DBAccess.Autor)convert.ConvertToDBModel(entitet));
				db.SaveChanges();
			}
		}

		/// 
		/// <param name="id"></param>
		public override void Delete(int id){
            using (var db = AteljeDB.Instance())
            {
				if(db.Autors.Where(x => x.Id == id).Count() != 0)
                {
					db.Autors.Remove(db.Autors.Where(x => x.Id == id).First());
					db.SaveChanges();
                }
				else
                {
					throw new Exception("Autor ne postoji.");
                }
            }
		}

		public override List<EntitetSistema> Read(){
			var retVal = new List<EntitetSistema>();

			using (var db = AteljeDB.Instance())
            {
				IDBConvert convert = new DBConvertAutor();

				retVal.AddRange(db.Ateljes.Select(x => (Autor)convert.ConvertToWebModel(x)));
            }

			return retVal;
		}

		/// 
		/// <param name="noviEntitet"></param>
		public override void Update(EntitetSistema noviEntitet){
			var a = (Autor)noviEntitet;
			
			using (var db = AteljeDB.Instance())
            {
				if(db.Autors.Where(x => x.Id == a.Id).Count() != 0)
                {
					IDBConvert convert = new DBConvertAutor();

					var curr = db.Autors.Where(x => x.Id == a.Id).First();
					db.Autors.Remove(curr);
					db.Autors.Add((DBAccess.Autor)convert.ConvertToDBModel(a));
					db.SaveChanges();
                }
            }
		}

	}//end DBCRUDUmetnik

}//end namespace Atelje