///////////////////////////////////////////////////////////
//  DBCRUDAteljeCreate.cs
//  Implementation of the Class DBCRUDAteljeCreate
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:25 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class DBCRUDAteljeCreate : DBCRUDAteljeCommand {

		private EntitetSistema entiet;

		public DBCRUDAteljeCreate(){

		}

		~DBCRUDAteljeCreate(){

		}

		/// 
		/// <param name="entitet"></param>
		public void Create(EntitetSistema entitet){

		}

		/// 
		/// <param name="id"></param>
		public void Delete(int id){

		}

		public EntitetSistema Entiet{
			get{
				return entieti;
			}
			set{
				entieti = value;
			}
		}

		public void Execute(){

		}

		public void Unexecute(){

		}

	}//end DBCRUDAteljeCreate

}//end namespace Atelje