///////////////////////////////////////////////////////////
//  DBCRUDAteljeInvoker.cs
//  Implementation of the Class DBCRUDAteljeInvoker
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:26 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class DBCRUDAteljeInvoker {

		public static List<DBCRUDAteljeCommand> komande = new List<DBCRUDAteljeCommand>();
		public static int cntComm = 0;

		// a, b, c, d,

		public void AddComand(DBCRUDAteljeCommand command)
        {
            try
            {
				if(komande.Count > 0 && cntComm < komande.Count - 1)
					komande.RemoveRange(++cntComm, komande.Count - cntComm);
				
				komande.Add(command);
				cntComm = komande.Count - 1;
			}
			catch (Exception)
            {
				return;
            }
		}

		public DBCRUDAteljeInvoker(){}

		~DBCRUDAteljeInvoker(){

		}

		public void ExecuteLast(){
			komande[cntComm].Execute();
		}

		public void Redo(){
			if(cntComm + 1 < komande.Count)
				komande[++cntComm].Execute();
		}

		public void Undo(){
			if(cntComm > -1)
				komande[cntComm--].Unexecute();
		}

	}//end DBCRUDAteljeInvoker

}//end namespace Atelje