///////////////////////////////////////////////////////////
//  DBCRUDUmetnik.cs
//  Implementation of the Class DBCRUDUmetnik
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:24 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using DBAccess;

using Atelje;
using System.Linq;

namespace Atelje {
	public class DBCRUDUmetnik : DBCRUD {

		public int CreatedId { get; set; }
		

		public DBCRUDUmetnik(){

		}

		~DBCRUDUmetnik(){

		}

		public Autor Exists(Autor autor)
        {
			Autor retVal = null;
			AteljeDB db;
            lock (db = AteljeDB.Instance())
            {
				konverzija = new DBConvertAutor();
				var aNew = (DBAccess.Autor)konverzija.ConvertToDBModel(autor);

				var find = db.Autors.Where(x =>
					x.GodinaRodjenja == (aNew.GodinaRodjenja) &&
					x.GodinaSmrti == (aNew.GodinaSmrti) &&
					x.Ime ==(aNew.Ime) &&
					x.Prezime == (aNew.Prezime) &&
					x.UmetnickiPravac == (int)aNew.UmetnickiPravac
					);

				if (find.ToList().Count > 0)
                {
					retVal = (Autor)konverzija.ConvertToWebModel(find.First());
                }
            }

			return retVal;
        }

		/// 
		/// <param name="entitet"></param>
		public override void Create(EntitetSistema entitet){
			AteljeDB db;
			lock (db = AteljeDB.Instance())
            {
				konverzija = new DBConvertAutor();

				var dbEnt = (DBAccess.Autor)konverzija.ConvertToDBModel(entitet);

				db.Autors.Add(dbEnt);
				db.SaveChanges();
				CreatedId = dbEnt.Id;
			}
		}

		/// 
		/// <param name="id"></param>
		public override void Delete(int id){
			AteljeDB db;
            lock (db = AteljeDB.Instance())
            {
				if (db.Autors.Where(x => x.Id == id).Count() != 0)
				{
					db.Autors.Remove(db.Autors.Where(x => x.Id == id).First());
					var dela = db.UmetnickoDeloes.Where(x => x.AutorId == id);
					if(dela.Count() > 0)
                    {
						db.UmetnickoDeloes.RemoveRange(dela);
                    }

					db.SaveChanges();
				}
				else
				{
					throw new Exception("Autor ne postoji.");
				}
			}
		}

		public override List<EntitetSistema> Read(){
			var retVal = new List<EntitetSistema>();
			AteljeDB db;

            lock (db = AteljeDB.Instance())
            {
				konverzija = new DBConvertAutor();

                foreach (var a in db.Autors)
                {
					retVal.Add((Autor)konverzija.ConvertToWebModel(a));
                }
			}

			return retVal;
		}

		/// 
		/// <param name="noviEntitet"></param>
		public override void Update(EntitetSistema noviEntitet){
			var a = (Autor)noviEntitet;
			AteljeDB db;
            lock (db = AteljeDB.Instance())
            {
				var currAt = db.Autors.Where(x => x.Id == a.Id);

				if(currAt.Count() > 0)
                {
					var udArr = new List<DBAccess.UmetnickoDelo>();

					foreach (var ud in db.UmetnickoDeloes)
					{
						if (ud.AutorId == currAt.First().Id)
						{
							udArr.Add(ud);
							db.UmetnickoDeloes.Remove(ud);
						}
					}

					db.SaveChanges();

					konverzija = new DBConvertAutor();

					db.Autors.Remove(currAt.First());
					var noviDb = (DBAccess.Autor)konverzija.ConvertToDBModel(noviEntitet);
					db.Autors.Add(noviDb);
					db.SaveChanges();
				}
			}
		}

	}//end DBCRUDUmetnik

}//end namespace Atelje