///////////////////////////////////////////////////////////
//  DBCRUDKorisnik.cs
//  Implementation of the Class DBCRUDKorisnik
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:24 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class DBCRUDKorisnik : DBCRUD {

		public DBCRUDKorisnik(){

		}

		~DBCRUDKorisnik(){

		}

		/// 
		/// <param name="entitet"></param>
		public void Create(EntitetSistema entitet){

		}

		/// 
		/// <param name="id"></param>
		public void Delete(int id){

		}

		/// 
		/// <param name="korisnickoIme"></param>
		/// <param name="lozinkaHash"></param>
		public bool Exists(string korisnickoIme, string lozinkaHash){

			return false;
		}

		public List<EntitetSistema> Read(){

			return null;
		}

		/// 
		/// <param name="noviEntitet"></param>
		public void Update(EntitetSistema noviEntitet){

		}

	}//end DBCRUDKorisnik

}//end namespace Atelje