///////////////////////////////////////////////////////////
//  DBCRUDAteljeInvoker.cs
//  Implementation of the Class DBCRUDAteljeInvoker
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:26 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
namespace Atelje {
	public class DBCRUDAteljeInvoker {

		public List<DBCRUDAteljeCommand> komande;

		public DBCRUDAteljeInvoker(){

		}

		~DBCRUDAteljeInvoker(){

		}

		public void ExecuteLast(){

		}

		public void Redo(){

		}

		public void Undo(){

		}

	}//end DBCRUDAteljeInvoker

}//end namespace Atelje