///////////////////////////////////////////////////////////
//  IDBConvert.cs
//  Implementation of the Interface IDBConvert
//  Generated by Enterprise Architect
//  Created on:      02-Oct-2021 4:44:23 PM
//  Original author: acast
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Atelje;
using DBAccess;

namespace Atelje {
	public interface IDBConvert  {

		/// 
		/// <param name="webModel"></param>
		DBEntity ConvertToDBModel(EntitetSistema webModel);

		/// 
		/// <param name="dbModel"></param>
		EntitetSistema ConvertToWebModel(DBEntity dbModel);
	}//end IDBConvert

}//end namespace Atelje